#!/bin/bash

set -eu

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

ynh_clean_setup () {
# Nettoyage des résidus d'installation non pris en charge par le script remove.
	if test -n "$PID_TAIL"
	then
		SUPPRESS_WARNING kill -s 15 $PID_TAIL	# Arrête l'exécution de tail.
		sudo rm -f "$tempfile"
	fi
	echo ""
}
ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
is_public=$YNH_APP_ARG_IS_PUBLIC
path_url="" # Assure la compatibilité avec les fonctions utilisant $path_url
admin_name=$YNH_APP_ARG_ADMIN_NAME
app=$YNH_APP_INSTANCE_NAME
secret=$(ynh_string_random)
#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================

if sudo yunohost domain list | grep -q $domain	# Vérifie la liste des domaines
then	# Si le domaine existe dans Yunohost
	if sudo yunohost app map | grep -q $domain	# Vérifie la liste des apps par domaine
	then 	# Si une app est installée sur ce domaine.
		WARNING echo "An app is already installed on the domain $domain. Mypads needs a whole domain or subdomain to himself."
	fi
fi

CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set "$app" admin_name "$admin_name"
ynh_app_setting_set "$app" secret "$secret"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================

port=$(ynh_find_port 4567)	# Cherche un port libre.
ynh_app_setting_set $app port $port

#=================================================
# INSTALL DEPENDENCIES
#=================================================

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
sudo apt-get update
sudo apt-get install -yy -qq mongodb-org

#=================================================
# INSTALL NODEJS
#=================================================
version=6.2.0
ynh_install_nodejs 6.2.0

#=================================================
# CREATE DEDICATED USER
#=================================================

ynh_system_user_create $app /home/$app	# Créer un utilisateur système dédié à l'app

#=================================================
# SPECIFIC SETUP
#=================================================
# HANDLE LOG FILES AND LOGROTATE
#=================================================

# Créer le dossier de log
sudo mkdir -p /var/log/$app
sudo touch /var/log/$app/nodebb.log
install_log=/var/log/$app/installation.log
sudo touch $install_log
sudo chown $app -R /var/log/$app
sudo chown admin -R $install_log

# Configuration de logrotate
ynh_use_logrotate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

final_path=/var/www/$app
ynh_app_setting_set $app final_path $final_path
SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
sudo chmod 755 $final_path -R
sudo chown www-data:www-data $final_path -R

#=================================================
# BEGINING OF THE INSTALLATION
#=================================================

sudo service mongod start
script_dir="$PWD"
pushd "$final_path"
ynh_use_nodejs
sudo_path npm install --production >> $install_log 2>&1
sudo_path npm install -g mongo
popd

sudo yunohost firewall allow Both $port

#=================================================
# CREATE A SQL BDD
#=================================================

pushd $final_path
dbname=$app
dbuser=$app
dbpass=$(ynh_string_random)
sudo mongo --shell "$dbname" --eval 'db.createUser( { user: "'${dbuser}'", pwd: "'${dbpass}'", roles: [ "readWrite" ] } );' <<< exit
sudo mongo --shell "$dbname" --eval 'db.grantRolesToUser("'${dbuser}'",[{ role: "clusterMonitor", db: "admin" }]);' <<< exit
popd

#=================================================
# Modify Nginx configuration file and copy it to Nginx conf directory
#=================================================

ynh_nginx_config
nginxconf=/etc/nginx/conf.d/$domain.d/$app.conf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf
ynh_systemd_config
ynh_replace_string "__NODEJS__" "$nodejs_use_version" "/etc/systemd/system/$app.service"
ynh_replace_string "__ENV_PATH__" "$PATH" "/etc/systemd/system/$app.service"
ynh_replace_string "__NODE__" "$nodejs_path" "/etc/systemd/system/$app.service"

#=================================================
# CONFIGURE SERVER.JS	
#=================================================

sudo mv ../conf/config.json $final_path/config.json
sudo sed -i "s@__URL__@$domain@g" $final_path/config.json
sudo sed -i "s@__PORT__@$port@g" $final_path/config.json
sudo sed -i "s@__SECRET__@$secret@g" $final_path/config.json
sudo sed -i "s@dbuser@$dbuser@g" $final_path/config.json
sudo sed -i "s@dbname@$dbname@g" $final_path/config.json
sudo sed -i "s@dbpass@$dbpass@g" $final_path/config.json

#=================================================
# CONFIGURE NODEBB
#=================================================

pushd $final_path
sudo chown -R $app: $final_path
sudo_path ./nodebb setup <<< \
     "$admin_name"
popd

sudo chown -R nodebb:nodebb $final_path

#=================================================
# START NodeBB IN BACKGROUND
#=================================================

cat /etc/systemd/system/$app.service
sudo systemctl daemon-reload
sudo systemctl enable "$app".service

#=================================================
# START ETHERPAD IN BACKGROUND
#=================================================

WARNING echo "Démarrage d'etherpad"
tempfile="$(mktemp)"
tail -f -n1 /var/log/$app/etherpad.log > "$tempfile" &	# Suit le démarrage dans le log
PID_TAIL=$!	# Récupère le PID de la commande tail, qui est passée en arrière plan.
sudo systemctl start $app     # Démarre Nodebb. Le démarrage est fait le plus tôt possible, car il est très long...

#=================================================
# ENABLE SERVICE IN ADMIN PANEL
#=================================================

# Ajoute le service au monitoring de Yunohost.
sudo yunohost service add $app --log "/var/log/$app/nodebb.log"

#=================================================
# SETUP SSOWAT
#=================================================

if [ "$is_public" = 0 ];
then
  ynh_app_setting_set "$app" unprotected_uris "/"
fi

#=================================================
# RELOAD NGINX
#=================================================

sudo systemctl reload nginx

#=================================================
# CHECK ETHERPAD STARTING
#=================================================

for i in `seq 1 120`
do	# La boucle attend le démarrage d'etherpad. Ou 2 minutes. Cette boucle évite simplement un 502 au début, car le démarrage est long...
	# Si le log annonce une première fois le démarrage d'etherpad, applique la langue de mypads et redémarre le service.
	WARNING echo "Le service $app a démarré correctement."
	sudo systemctl restart $app
	cat /dev/null > "$tempfile"	# Purge le log de suivi du démarrage.
	i=1

	WARNING echo -n "."
	sleep 1
	break
done
SUPPRESS_WARNING kill -s 15 $PID_TAIL	# Arrête l'exécution de tail.
ynh_secure_remove "$tempfile"
