#!/bin/bash

#https://docs.nodebb.org/configuring/upgrade/

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

pushd $install_dir
	ynh_use_nodejs
	# Shut down your forum
	git config --system --add safe.directory $install_dir
	ynh_exec_as $app env "$ynh_node_load_PATH" $install_dir/nodebb stop
	# Grab the latest and greatest code
	git fetch    								# Grab the latest code from the NodeBB Repository
	git reset --hard origin/$nodebb_version		# Replace v1.12.x with the branch name!
	# Run the NodeBB upgrade script
	ynh_exec_as $app $ynh_node_load_PATH $install_dir/nodebb upgrade 2>/dev/null 
popd

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Install Nodejs
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="Forum software" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
